-- Insert statement for the Player table

INSERT INTO player (team, playername, pos) VALUES
('MEX','José Raúl Rangel','GK'),
('MEX','Jorge Eduardo Sanchez','DEF'),
('MEX','César Jasib Montes','DEF'),
('MEX','Edson Omar Alvarez','DEF'),
('MEX','Johan Felipe Vasquez','DEF'),
('MEX','Erik Antonio Lira','MID'),
('MEX','Luis Francisco Romo','MID'),
('MEX','Álvaro Fidalgo','MID'),
('MEX','Raúl Alonso Jimenez','FWD'),
('MEX','Ernesto Alexis Vega','FWD'),
('MEX','Santiago Tomás Gimenez','FWD'),
('MEX','Carlos Acevedo','GK'),
('MEX','Francisco Guillermo Ochoa','GK'),
('MEX','Armando Gonzalez','FWD'),
('MEX','Israel Reyes','DEF'),
('MEX','Julián Andrés Quinones','FWD'),
('MEX','Orbelín Pineda','MID'),
('MEX','Obed Goméz Vargas','MID'),
('MEX','Gilberto Rafael Mora','MID'),
('MEX','Mateo Chavez','DEF'),
('MEX','César Saúl Huerta','FWD'),
('MEX','Guillermo Martinez','FWD'),
('MEX','Jesús Daniel Gallardo','DEF'),
('MEX','Luis Gerardo Chavez','MID'),
('MEX','Roberto Carlos Alvarado','FWD'),
('MEX','Brian Gutierrez','MID'),
('RSA','Ronwen Hayden Williams','GK'),
('RSA','Tholo Thabang Matuludi','DEF'),
('RSA','Khulumani Ndamane','DEF'),
('RSA','Teboho Mokoena','MID'),
('RSA','Thalente Wandile Mbatha','MID'),
('RSA','Aubrey Maphosa Modiba','DEF'),
('RSA','Oswin Reagan Appollis','FWD'),
('RSA','Tshepang Moremi','FWD'),
('RSA','Lyle Brent Foster','FWD'),
('RSA','Relebohile Mofokeng','FWD'),
('RSA','Themba Zwane','MID'),
('RSA','Thapelo Maseko','FWD'),
('RSA','Sphephelo S''miso Sithole','MID'),
('RSA','Mbekezeli Mfanufikile Mbokazi','DEF'),
('RSA','Iqraam Rayners','FWD'),
('RSA','Sipho Justin Chaine','GK'),
('RSA','Sekotori Evidence Makgopa','FWD'),
('RSA','Samukele Alucious Kabini','DEF'),
('RSA','Nkosinathi Emmanuel Sibisi','DEF'),
('RSA','Khuliso Johnson Mudau','DEF'),
('RSA','Ime Daniel Okon','DEF'),
('RSA','Stuart Ricardo Goss','GK'),
('RSA','Jayden Oswin Adams','MID'),
('RSA','Olwethu Mpilwenhle Makhanya','DEF'),
('RSA','Kamogelo Michael Sebelebele','FWD'),
('RSA','Bradley Paul Cross','DEF'),
('KOR','Seunggyu Kim','GK'),
('KOR','Hanbeom Lee','DEF'),
('KOR','Gihyuk Lee','MID'),
('KOR','Minjae Kim','DEF'),
('KOR','Taehyeon Kim','DEF'),
('KOR','Inbeom Hwang','MID'),
('KOR','Heung Min Son','FWD'),
('KOR','Seungho Paik','MID'),
('KOR','Guesung Cho','FWD'),
('KOR','Jae Sung Lee','MID'),
('KOR','Hee Chan Hwang','MID'),
('KOR','Bumkeun Song','GK'),
('KOR','Taeseok Lee','DEF'),
('KOR','Wije Cho','DEF'),
('KOR','Moonhwan Kim','DEF'),
('KOR','Jinseob Park','DEF'),
('KOR','Junho Bae','MID'),
('KOR','Hyeongyu Oh','FWD'),
('KOR','Kangin Lee','MID'),
('KOR','Hyunjun Yang','MID'),
('KOR','Hyeonwoo Jo','GK'),
('KOR','Youngwoo Seol','DEF'),
('KOR','Jens Castrop','DEF'),
('KOR','Jingyu Kim','MID'),
('KOR','Jisung Eom','MID'),
('KOR','Donggyeong Lee','MID'),
('CZE','Mat ě j Kovar','GK'),
('CZE','David Zima','DEF'),
('CZE','Tomáš Holes','DEF'),
('CZE','Robin Hranac','DEF'),
('CZE','Vladimír Coufal','DEF'),
('CZE','ě pán Chaloupek','DEF'),
('CZE','Ladislav Krejci','DEF'),
('CZE','Vladimír Darida','MID'),
('CZE','Adam Hlozek','FWD'),
('CZE','Patrik Schick','FWD'),
('CZE','Jan Kuchta','FWD'),
('CZE','Lukáš Cerv','MID'),
('CZE','Mojmír Chytil','FWD'),
('CZE','David Jurasek','DEF'),
('CZE','Pavel Sulc','FWD'),
('CZE','Jind ř ich Stanek','GK'),
('CZE','Lukáš Provod','MID'),
('CZE','Michal Sadilek','MID'),
('CZE','Tomáš Chory','FWD'),
('CZE','Jaroslav Zeleny','DEF'),
('CZE','David Doudera','DEF'),
('CZE','Tomáš Soucek','MID'),
('CZE','Lukáš Hornicek','GK'),
('CZE','Alexandr Sojka','MID'),
('CZE','Hugo Sochurek','MID'),
('CZE','Denis Visinsky','FWD'),
('CAN','Dayne Tristan St. Clair','GK'),
('CAN','Alistair William Johnston','DEF'),
('CAN','Alfie Charles Jones','DEF'),
('CAN','Luc De Fougerolles','DEF'),
('CAN','Joel Robert Waterman','DEF'),
('CAN','Mathieu Choiniere','MID'),
('CAN','Stephen Eustaquio','MID'),
('CAN','Ismaël Kenneth Jordan Kone','MID'),
('CAN','Cyle Christopher Larin','FWD'),
('CAN','Jonathan Christian David','FWD'),
('CAN','Liam Alan Millar','MID'),
('CAN','Tanitoluwa Oluwatimilehin Oluwaseyi','FWD'),
('CAN','Derek Austin Cornelius','DEF'),
('CAN','Jacob Everett Shaffelburg','MID'),
('CAN','Moïse Bombito Bombito','DEF'),
('CAN','Maxime Crepeau','GK'),
('CAN','Tajon Trevor Buchanan','FWD'),
('CAN','Owen Olamidayo Goodman','GK'),
('CAN','Alphonso Boyle Davies','DEF'),
('CAN','Ali Ahmed','FWD'),
('CAN','Jonathan Osorio','MID'),
('CAN','Richmond Mamah Laryea','DEF'),
('CAN','Niko Kristian Sigur','DEF'),
('CAN','Promise Oluwatobi Emmanuel David','FWD'),
('CAN','Nathan-Dylan Saliba','MID'),
('CAN','Jayden Nelson','FWD'),
('BIH','Nikola Vasilj','GK'),
('BIH','Nihad Mujakic','DEF'),
('BIH','Dennis Hadzikadunic','DEF'),
('BIH','Tarik Muharemovic','DEF'),
('BIH','Sead Kolasinac','DEF'),
('BIH','Benjamin Tahirovic','MID'),
('BIH','Amar Dedic','DEF'),
('BIH','Armin Gigovic','MID'),
('BIH','Samed Bazdar','FWD'),
('BIH','Ermedin Demirovic','FWD'),
('BIH','Edin Dzeko','FWD'),
('BIH','Mladen Jurkas','GK'),
('BIH','Ivan Basic','MID'),
('BIH','Ivan Sunjic','MID'),
('BIH','Amar Memic','MID'),
('BIH','Amir Hadziahmetovic','MID'),
('BIH','Dzenis Burnic','MID'),
('BIH','Nikola Katic','DEF'),
('BIH','Kerim Alajbegovic','FWD'),
('BIH','Esmir Bajraktarevic','FWD'),
('BIH','Stjepan Radeljic','DEF'),
('BIH','Martin Zlomislic','GK'),
('BIH','Haris Tabakovic','FWD'),
('BIH','Arjan Malic','DEF'),
('BIH','Jovo Lukic','FWD'),
('BIH','Ermin Mahmic','MID'),
('QAT','Ibrahim Mahmoud Abunada','GK'),
('QAT','Miguel Pedro','DEF'),
('QAT','Michel Lucas','DEF'),
('QAT','Gueye Issa Laye','DEF'),
('QAT','Gaber Jassem','DEF'),
('QAT','Hatim Abdulaziz Hatem','MID'),
('QAT','Alaaeldin Ahmed','FWD'),
('QAT','Junior Edmilson','FWD'),
('QAT','Mohammed Mohammed Muntari','FWD'),
('QAT','Khalid Hassan Alhaydos','FWD'),
('QAT','Hassan Akram','FWD'),
('QAT','Karim Karim Boudiaf','MID'),
('QAT','Mohamed Ayoub Aloui','DEF'),
('QAT','Elamin Homam','DEF'),
('QAT','Abdurisag Yusuf Abdurisag','FWD'),
('QAT','KHOUKHIBoualem Boualem','DEF'),
('QAT','Mohamed Ahmed Alganehi','MID'),
('QAT','Hussain Sultan','DEF'),
('QAT','Ali Zainelabdeen Almoez','FWD'),
('QAT','Fathy Ahmed Fathy','MID'),
('QAT','Zakaria Salah Zakaria','GK'),
('QAT','Aissa Meshaal Barsham','GK'),
('QAT','Omer Assim Madibo','MID'),
('QAT','Mohammad Tahsin','FWD'),
('QAT','Alhussein Alhashmi','DEF'),
('QAT','Naceur Mohamed Manai','FWD'),
('SUI','Gregor Kobel','GK'),
('SUI','Miro Max Maria Muheim','DEF'),
('SUI','Silvan Dominic Widmer','DEF'),
('SUI','Nico Elvedi','DEF'),
('SUI','Manuel Obafemi Akanji','DEF'),
('SUI','Denis Lemi Zakaria','MID'),
('SUI','Breel Donald Embolo','FWD'),
('SUI','Remo Marco Freuler','MID'),
('SUI','Johan Kula Manzambi','MID'),
('SUI','Granit Xhaka','MID'),
('SUI','Dan Ndoye','FWD'),
('SUI','Yvon Landry Mvogo','GK'),
('SUI','Ricardo Ivan Rodriguez','DEF'),
('SUI','Ardon Jashari','MID'),
('SUI','Djibril Ibrahima Sow','MID'),
('SUI','Christian Andreas Fassnacht','FWD'),
('SUI','Ruben Estephan Vargas','FWD'),
('SUI','Eray Ervin Coemert','DEF'),
('SUI','Noah Arinzechukwu Okafor','FWD'),
('SUI','Michel Aebischer','MID'),
('SUI','Marvin Keller','GK'),
('SUI','Fabian Rieder','MID'),
('SUI','Mohamed Zeki Amdouni','FWD'),
('SUI','Aurèle Florian Amenda','DEF'),
('SUI','Luca Antony Jaquez','DEF'),
('SUI','Cedric Jan Itten','FWD'),
('BRA','Ramsés Alisson','GK'),
('BRA','José Ederson Silva','MID'),
('BRA','Gabriel Gabriel Magalhaes','DEF'),
('BRA','MARQUINHOSMarcos','DEF'),
('BRA','Henrique','MID'),
('BRA','Sandro Alex','DEF'),
('BRA','José Vinicius','FWD'),
('BRA','GUIMARAESBruno Bruno','MID'),
('BRA','Matheus Matheus Cunha','FWD'),
('BRA','Neymar Neymar Jr','FWD'),
('BRA','Raphael Raphinha','FWD'),
('BRA','Weverton Weverton','GK'),
('BRA','Luiz Danilo','DEF'),
('BRA','Bremer Bremer','DEF'),
('BRA','PEREIRALeonardo Leo','DEF'),
('BRA','Douglas Douglas Santos','DEF'),
('BRA','Henrique Fabinho','MID'),
('BRA','Danilo Danilo Santos','MID'),
('BRA','Felipe Endrick','FWD'),
('BRA','Lucas Lucas Paqueta','MID'),
('BRA','Henrique André Luiz','FWD'),
('BRA','MARTINELLIGabriel Gabriel','FWD'),
('BRA','Ederson Ederson','GK'),
('BRA','IBANEZRoger Roger','DEF'),
('BRA','Thiago Igor Thiago','FWD'),
('BRA','Vitor Rayan','FWD'),
('MAR','Yassine Bounou','GK'),
('MAR','Achraf Hakimi','DEF'),
('MAR','Noussair Mazraoui','DEF'),
('MAR','Sofyan Amrabat','MID'),
('MAR','Marwane Saadane','DEF'),
('MAR','Ayyoub Bouaddi','MID'),
('MAR','Chemsdine Talbi','MID'),
('MAR','Azz-Eddine Ounahi','MID'),
('MAR','Soufiane Rahimi','FWD'),
('MAR','Brahim Diaz','FWD'),
('MAR','Ismael Saibari','MID'),
('MAR','Monir El Kajoui','GK'),
('MAR','Zakaria El Ouahdi','DEF'),
('MAR','Issa Laye Lucas Jean Diop','DEF'),
('MAR','Samir El Mourabet','MID'),
('MAR','Gessime Ben Youssef Mustapha Yassine','MID'),
('MAR','Mohamed Amine Sbai','FWD'),
('MAR','Chadi Riad','DEF'),
('MAR','Youssef Belammari','DEF'),
('MAR','Ayoub El Kaabi','FWD'),
('MAR','Ayoube Amaimouni','FWD'),
('MAR','Ahmed Reda Tagnaouti','GK'),
('MAR','Bilal El Khannouss','MID'),
('MAR','Neil Yoni El Aynaoui','MID'),
('MAR','Redouane Halhal','DEF'),
('MAR','Anass Salah Eddine','DEF'),
('HAI','Johny Placide','GK'),
('HAI','Carlens Jean Fedlaire Ruby Arcus','DEF'),
('HAI','Keeto Thermoncy','DEF'),
('HAI','Ricardo Ade','DEF'),
('HAI','Hannes Piterson Delcroix','DEF'),
('HAI','Carl Fred Sainte','MID'),
('HAI','Derrick Burckley Etienne','FWD'),
('HAI','Martin Yves Roberns Didier Experience','DEF'),
('HAI','Duckens Nazon','FWD'),
('HAI','Jean Ricner Bellegarde','MID'),
('HAI','Don Deedson Deedson','FWD'),
('HAI','Alexandre Jr Pierre','GK'),
('HAI','Markhus Lacroix','DEF'),
('HAI','Garven-Michee Metusala','DEF'),
('HAI','Ruben Fritzner Providence','FWD'),
('HAI','Lenny Alvin Pico Joseph','FWD'),
('HAI','Danley Jean Jacques','MID'),
('HAI','Wilson Isidor','FWD'),
('HAI','Yassin Enzo Fortune','FWD'),
('HAI','Frantzdy Pierrot','FWD'),
('HAI','Josue Jeremie Casimir','FWD'),
('HAI','Jean-Kévin Duverne','DEF'),
('HAI','Josue Duverger','GK'),
('HAI','Wilguens Raphael Polynice Paugain','DEF'),
('HAI','Dominique Celidor Simon','MID'),
('HAI','Olivier Woodensky Pierre','MID'),
('SCO','Angus Fraser James Gunn','GK'),
('SCO','Aaron Buchanan Hickey','DEF'),
('SCO','Andrew Henry Robertson','DEF'),
('SCO','Scott McTominay','MID'),
('SCO','Grant Campbell Hanley','DEF'),
('SCO','Kieran Tierney','DEF'),
('SCO','John McGinn','MID'),
('SCO','Tyler Robert Fletcher','MID'),
('SCO','Lyndon John Dykes','FWD'),
('SCO','Che Sac Everton Fred Adams','FWD'),
('SCO','Ryan Christie','MID'),
('SCO','Liam Patrick Kelly','GK'),
('SCO','Jack William Hendry','DEF'),
('SCO','Ross Cameron Stewart','FWD'),
('SCO','John Francis Souttar','DEF'),
('SCO','Dominic John Hyam','DEF'),
('SCO','Ben Gannon Gannon-Doak','FWD'),
('SCO','George David Eric Hirst','FWD'),
('SCO','Lewis Ferguson','MID'),
('SCO','Lawrence Shankland','FWD'),
('SCO','Craig Sinclair Gordon','GK'),
('SCO','Nathan Kenneth Patterson','DEF'),
('SCO','Kenny McLean','MID'),
('SCO','Anthony Ralston','DEF'),
('SCO','Findlay Kenneth Curtis','FWD'),
('SCO','Mc (SCO)','DEF'),
('USA','Matthew Charles Turner','GK'),
('USA','Sergiño Gianni Dest','DEF'),
('USA','Christopher Jeffrey Richards','DEF'),
('USA','Tyler Shaan Adams','MID'),
('USA','Antonee Robinson','DEF'),
('USA','Auston Levi-Jesaiah Trusty','DEF'),
('USA','Giovanni Alejandro Reyna','MID'),
('USA','Weston McKennie','MID'),
('USA','Ricardo Daniel Pepi','FWD'),
('USA','Christian Mate Pulisic','FWD'),
('USA','Brenden Russell Aaronson','FWD'),
('USA','Miles Gordon Robinson','DEF'),
('USA','Timothy Michael Ream','DEF'),
('USA','Sebastian Matthew Berhalter','MID'),
('USA','Cristian Roldan','MID'),
('USA','Alexander Michael Freeman','DEF'),
('USA','Malik Leon Tillman','MID'),
('USA','Maximilian Michael Arfsten','DEF'),
('USA','Haji Amir Wright','FWD'),
('USA','Folarin Jolaoluwa Balogun','FWD'),
('USA','Timothy Tarpeh Weah','FWD'),
('USA','Mc (USA)','DEF'),
('USA','Joseph Michael Scally','DEF'),
('USA','Matthew Andrew Geary Freese','GK'),
('USA','Christopher Keith Brady','GK'),
('USA','Alejandro Zendejas','FWD'),
('PAR','Roberto Junior Fernandez','GK'),
('PAR','Victor Gustavo Velazquez','DEF'),
('PAR','Omar Federico Alderete','DEF'),
('PAR','Juan Jose Caceres','DEF'),
('PAR','Fabián Cornelio Balbuena','DEF'),
('PAR','Júnior Osmar Ignacio Alonso','DEF'),
('PAR','Ramón Sosa','MID'),
('PAR','Diego Alexander Gomez','MID'),
('PAR','Arnaldo Antonio Sanabria','FWD'),
('PAR','Miguel Angel Almiron','MID'),
('PAR','Mauricio Mauricio','MID'),
('PAR','Orlando Daniel Gill','GK'),
('PAR','Jose Maria Canale','DEF'),
('PAR','Adrián Andrés Cubas','MID'),
('PAR','Gustavo Raul Gomez','DEF'),
('PAR','Damián Josue Bobadilla','MID'),
('PAR','Alejandro Sebastian Romero Gamarra','FWD'),
('PAR','Alex Adrian Arce','FWD'),
('PAR','Julio Cesar Enciso','FWD'),
('PAR','Braian Oscar Ojeda','MID'),
('PAR','Gabriel Avalos','FWD'),
('PAR','Gastón Hernán Olveira','GK'),
('PAR','Matias Galarza','MID'),
('PAR','Gustavo Ruben Caballero','MID'),
('PAR','Isidro Miguel Pitta','FWD'),
('PAR','Alexandro Maidana','DEF'),
('AUS','Mathew David Ryan','GK'),
('AUS','Milos Degenek','DEF'),
('AUS','Alessandro Circati','DEF'),
('AUS','Jacob Michael Italiano','DEF'),
('AUS','Jordan Jacob Bos','DEF'),
('AUS','Jason Kato Geria','DEF'),
('AUS','Mathew Allan Leckie','FWD'),
('AUS','Connor Isaac Metcalfe','MID'),
('AUS','Mohamed Toure','FWD'),
('AUS','Ajdin Hrustic','FWD'),
('AUS','Awer Bul Mabil','FWD'),
('AUS','Paul David Izzo','GK'),
('AUS','Aiden Connor Oneill','MID'),
('AUS','Cameron Peter Devlin','MID'),
('AUS','Kai Clifton Trewin','DEF'),
('AUS','Aziz Behich','DEF'),
('AUS','Nestory Irankunda','FWD'),
('AUS','Patrick Thomas Beach','GK'),
('AUS','Harry James Souttar','DEF'),
('AUS','Cristian Volpato','FWD'),
('AUS','Cameron Robert Burgess','DEF'),
('AUS','Jackson Alexander Irvine','MID'),
('AUS','Nishan Matthew Velupillay','FWD'),
('AUS','Paul Michael Junior Okon-Engstler','MID'),
('AUS','Lucas Herrington','DEF'),
('AUS','Tete Owen Yengi','FWD'),
('TUR','Fehmi Mert Gunok','GK'),
('TUR','Mehmet Zeki Celik','DEF'),
('TUR','Merih Demiral','DEF'),
('TUR','Ça ğ lar Soyuncu','DEF'),
('TUR','Salih Ozcan','MID'),
('TUR','Orkun Kokcu','MID'),
('TUR','Muhammed Kerem Akturkoglu','FWD'),
('TUR','Arda Guler','FWD'),
('TUR','Deniz Daniel Gul','FWD'),
('TUR','Hakan Calhanoglu','MID'),
('TUR','Kenan Yildiz','FWD'),
('TUR','Altay Bayindir','GK'),
('TUR','Evren Eren Elmali','DEF'),
('TUR','Abdülker Bardakci','DEF'),
('TUR','Ozan Muhammed Kabak','DEF'),
('TUR','Ismailİsma Yuksek','MID'),
('TUR','Can İrfan Kahveci','FWD'),
('TUR','Mert Muldur','DEF'),
('TUR','Yunus Akgun','FWD'),
('TUR','Ferdi Erenay Kadioglu','DEF'),
('TUR','Barı ş Alper Yilmaz','FWD'),
('TUR','Kaan Ayhan','MID'),
('TUR','Ugurcan Cakir','GK'),
('TUR','Oguz Aydin','FWD'),
('TUR','Samet Akaydin','DEF'),
('TUR','Can Yılmaz Uzun','FWD'),
('GER','Manuel Peter Neuer','GK'),
('GER','Antonio Ruediger','DEF'),
('GER','Waldemar Anton','DEF'),
('GER','Jonathan Glao Tah','DEF'),
('GER','Aleksandar Pavlovic','MID'),
('GER','Joshua Walter Kimmich','DEF'),
('GER','Kai Lukas Havertz','FWD'),
('GER','Leon Christoph Goretzka','MID'),
('GER','Jamie Jaleel Jeremy Leweling','MID'),
('GER','Jamal Musiala','MID'),
('GER','Nick Woltemade','FWD'),
('GER','Oliver Baumann','GK'),
('GER','Pascal Alexander GROß GROß Gross','MID'),
('GER','Maximilian Beier','FWD'),
('GER','Nico Cédric Schlotterbeck','DEF'),
('GER','Angelo Nicolas Stiller','MID'),
('GER','Florian Richard Wirtz','MID'),
('GER','Nathaniel Christopher Brown','DEF'),
('GER','Leroy Aziz Sane','MID'),
('GER','Nadiem Amiri','MID'),
('GER','Alexander Nuebel','GK'),
('GER','David Raum','DEF'),
('GER','Felix Kalu Nmecha','MID'),
('GER','Malick Thiaw','DEF'),
('GER','Forzan Assan Ouedraogo','MID'),
('GER','Deniz Undav','FWD'),
('CUW','Eloy Victor Room','GK'),
('CUW','Shurandy Ruggerio Sambo','DEF'),
('CUW','Juriën Godfried Juan Gaari','DEF'),
('CUW','Róshón Felix Romar Jordan Van Eijma','DEF'),
('CUW','Sherel Constancio Floranus','DEF'),
('CUW','Godfried Roemeratoe','MID'),
('CUW','Juninho Gracielo Bacuna','MID'),
('CUW','Livano Shyron Liomar Comenencia','MID'),
('CUW','Jürgen Leonardo Locadia','FWD'),
('CUW','Leandro Jones Johan Bacuna','MID'),
('CUW','Jeremy Cornelis Jacobus Antonisse','FWD'),
('CUW','Juniffer Naigelino Hansen','FWD'),
('CUW','Tyrese Yurvencey Noslin','FWD'),
('CUW','Kenji Joël Gorre','FWD'),
('CUW','Jainel Archenir Martha','MID'),
('CUW','Jearl Erwin Margaritha','FWD'),
('CUW','Brandley Mack-Olien Kuwas','FWD'),
('CUW','Armando Maria Obispo','DEF'),
('CUW','Gervane Zjandric Adonnis Kastaneer','FWD'),
('CUW','Joshua Benjamin Brenet','DEF'),
('CUW','Tahith Jose Girigorio Djorkaef Chong','MID'),
('CUW','Kevin Antonio Felida','MID'),
('CUW','Riechedly Guillermo Bazoer','DEF'),
('CUW','Deveron Lenny Fonville','DEF'),
('CUW','Tyrick Jeremy Bodak','GK'),
('CUW','Trevor Irving Doornbusch','GK'),
('CIV','Yahia Fofana','GK'),
('CIV','Ousmane Diomande','DEF'),
('CIV','N''clomande Ghislain Konan','DEF'),
('CIV','Jean Michael Seri','MID'),
('CIV','Wilfried Stephane Singo','DEF'),
('CIV','Seko Mohamed Fofana','MID'),
('CIV','Odilon Dorgeless Kossounou','DEF'),
('CIV','Franck Yannick Kessie','MID'),
('CIV','Ange-Yoan Laurent Bonny','FWD'),
('CIV','Simon Adingra','FWD'),
('CIV','Yan Diomande','FWD'),
('CIV','Elye Delmas Wahi','FWD'),
('CIV','Christopher Tea Domoraud Operi','DEF'),
('CIV','Oumar Diakite','FWD'),
('CIV','Amad Diallo','FWD'),
('CIV','Mohamed Kone','GK'),
('CIV','Guela Maho-Lewis Doue','DEF'),
('CIV','Ibrahim Sangare','MID'),
('CIV','Nicolas Pepe','FWD'),
('CIV','Emmanuel Elysee Djedje Agbadou','DEF'),
('CIV','Obite Evan Ndicka','DEF'),
('CIV','Evann Ludovic Vidjannagni Guessand','FWD'),
('CIV','Alban-Marc Lafont','GK'),
('CIV','Bazoumana Toure','FWD'),
('CIV','Parfait Guiagon','MID'),
('CIV','Christ Ravynel Inao Oulai','MID'),
('ECU','Hernán Ismael Galindez','GK'),
('ECU','Félix Eduardo Torres','DEF'),
('ECU','Piero Martin Hincapie','DEF'),
('ECU','Joel Leandro Ordonez','DEF'),
('ECU','Jordy Jose Alcivar','MID'),
('ECU','Willian Joel Pacho','DEF'),
('ECU','Pervis Josue Estupinan','DEF'),
('ECU','Anthony Lenin Valencia','MID'),
('ECU','John Yeboah','FWD'),
('ECU','Ray Kendry Paez','MID'),
('ECU','Kevin Jose Rodriguez','FWD'),
('ECU','Wellington Moisés Ramirez','GK'),
('ECU','Enner Remberto Valencia','FWD'),
('ECU','Alan Steve Minda','MID'),
('ECU','Pedro Jeampierre Vite','MID'),
('ECU','Jordy Josue Caicedo','FWD'),
('ECU','Ángelo Smit Preciado','DEF'),
('ECU','Denil Daniel Castillo','MID'),
('ECU','Gonzalo Jordy Plata','FWD'),
('ECU','Nilson David Angulo','FWD'),
('ECU','Alan Steven Franco','MID'),
('ECU','Gonzalo Roberto Valle','GK'),
('ECU','Moisés Isaac Caicedo','MID'),
('ECU','Jeremy Alberto Arevalo','FWD'),
('ECU','Jackson Gabriel Porozo','DEF'),
('ECU','Yaimar Abel Medina','DEF'),
('NED','Bart Verbruggen','GK'),
('NED','Lutsharel Emiliano Geertruida','DEF'),
('NED','Marten Elco De Roon','MID'),
('NED','Virgil Van Dijk','DEF'),
('NED','Nathan Benjamin Ake','DEF'),
('NED','Paul Jan-Paul Van Hecke','DEF'),
('NED','Justin Dean Kluivert','MID'),
('NED','Ryan Jiro Gravenberch','MID'),
('NED','Wout François Maria Weghorst','FWD'),
('NED','Memphis Depay','FWD'),
('NED','Cody Mathès Gakpo','FWD'),
('NED','Mats Henrik Berne Wieffer','DEF'),
('NED','Robin Gerardus Petrus Roefs','GK'),
('NED','Tijjani Martinus Jan Reijnders','MID'),
('NED','Micky Van De Ven','DEF'),
('NED','Guus Berend Til','MID'),
('NED','Noa Noëll Lang','FWD'),
('NED','Donyell Malen','FWD'),
('NED','Brian Ebenezer Adjei Brobbey','FWD'),
('NED','Teun Koopmeiners','MID'),
('NED','Frenkie De Jong','MID'),
('NED','Denzel Justus Morris Dumfries','DEF'),
('NED','Mark Maria Hubertus Flekken','GK'),
('NED','Crysencio Jilbert Sylverio Cir Summerville','FWD'),
('NED','Jorrel Evan Hato','DEF'),
('NED','Quinten Ryan Crispito Timber','MID'),
('JPN','Zion Suzuki','GK'),
('JPN','Yukinari Sugawara','DEF'),
('JPN','Shogo Taniguchi','DEF'),
('JPN','Kou Itakura','DEF'),
('JPN','Yuto Nagatomo','DEF'),
('JPN','Shuto Machino','FWD'),
('JPN','Ao Tanaka','MID'),
('JPN','Takefusa Kubo','MID'),
('JPN','Keisuke Goto','FWD'),
('JPN','Ritsu Doan','MID'),
('JPN','Daizen Maeda','MID'),
('JPN','Keisuke Osako','GK'),
('JPN','Keito Nakamura','MID'),
('JPN','Junya Ito','MID'),
('JPN','Daichi Kamada','MID'),
('JPN','Tsuyoshi Watanabe','DEF'),
('JPN','Yuito Suzuki','MID'),
('JPN','Ayase Ueda','FWD'),
('JPN','Koki Ogawa','FWD'),
('JPN','Ayumu Seko','DEF'),
('JPN','Hiroki Ito','DEF'),
('JPN','Takehiro Tomiyasu','DEF'),
('JPN','Tomoki Hayakawa','GK'),
('JPN','Kaishu Sano','MID'),
('JPN','Junnosuke Suzuki','DEF'),
('JPN','Kento Shiogai','FWD'),
('SWE','Jacob Mikael Widell Zetterstrom','GK'),
('SWE','Gustaf Johan Lagerbielke','DEF'),
('SWE','Victor Jörgen Lindelof','DEF'),
('SWE','Isak Malcolm Kwaku Hien','DEF'),
('SWE','Gabriel Johan Gudmundsson','DEF'),
('SWE','Herman Nils Johansson','DEF'),
('SWE','Lucas Erik Holger Bergvall','MID'),
('SWE','Daniel Jonathan Svensson','DEF'),
('SWE','Alexander Isak','FWD'),
('SWE','Erik Benjamin Nygren','MID'),
('SWE','Anthony David Junior Elanga','FWD'),
('SWE','Tobias Viktor Johansson','GK'),
('SWE','Ken Sema','MID'),
('SWE','Hjalmar Ekdal','DEF'),
('SWE','Carl Anders Theodor Starfelt','DEF'),
('SWE','Jesper Kewe Karlstrom','MID'),
('SWE','Viktor Einar Gyokeres','FWD'),
('SWE','Yasin Ayari','MID'),
('SWE','Mattias Olof Svanberg','MID'),
('SWE','Eric Anders Smith','DEF'),
('SWE','Alexander Olof Bernhardsson','DEF'),
('SWE','Besfort Zeneli','MID'),
('SWE','Bo Kristoffer Nordfeldt','GK'),
('SWE','Elliot Karl Stroud','DEF'),
('SWE','Håkan Gustaf Nilsson','FWD'),
('SWE','Taha Abdi Ali','FWD'),
('TUN','Abdelmouhib Chamakh','GK'),
('TUN','Ali Abdi','DEF'),
('TUN','Montassar Omar Talbi','DEF'),
('TUN','Omar Rekik','DEF'),
('TUN','Adam Arous','DEF'),
('TUN','Dylan Daniel Mahmoud Bronn','DEF'),
('TUN','Mohamed Elyes Achouri','FWD'),
('TUN','Elias Saad','FWD'),
('TUN','Hazem Mastouri','FWD'),
('TUN','Hannibal Mejbri','MID'),
('TUN','Ismael Seifallah Gharbi','MID'),
('TUN','Ahmed Mortadha Ben Ouanes','DEF'),
('TUN','Rani Khedira','MID'),
('TUN','Khalil Ayari','MID'),
('TUN','Mohamed Hadj Mahmoud','MID'),
('TUN','Aymen Dahmen','GK'),
('TUN','Ellyes Joris Skhiri','MID'),
('TUN','Rayan Elloumi','FWD'),
('TUN','Firas Chaouat','FWD'),
('TUN','Yan Valery','DEF'),
('TUN','Mohamed Amine Ben Hmida','DEF'),
('TUN','Sabri Ben Hessen','GK'),
('TUN','Moutaz Neffati','DEF'),
('TUN','Raed Chikhaoui','DEF'),
('TUN','Anis Slimane','MID'),
('TUN','Sebastian Tounekti','MID'),
('BEL','Thibaut Nicolas Courtois','GK'),
('BEL','Zeno Koen Debast','DEF'),
('BEL','Arthur Nicolas Theate','DEF'),
('BEL','Brandon Erik Mechele','DEF'),
('BEL','Maxim Peter De Cuyper','DEF'),
('BEL','Axel Laurent Witsel','MID'),
('BEL','Kevin De Bruyne','MID'),
('BEL','Youri Marion Tielemans','MID'),
('BEL','Romelu Lukaku','FWD'),
('BEL','Leandro Trossard','FWD'),
('BEL','Jeremy Baffour Doku','FWD'),
('BEL','Senne Lammens','GK'),
('BEL','Mike Louis Penders','GK'),
('BEL','Dodi Lukebakio','FWD'),
('BEL','Thomas Andre Meunier','DEF'),
('BEL','Koni De Winter','DEF'),
('BEL','Charles Marc De Ketelaere','FWD'),
('BEL','Joaquin Ronny Seys','DEF'),
('BEL','Diego Manuel Moreira','MID'),
('BEL','Hans Vanaken','MID'),
('BEL','Timothy Castagne','DEF'),
('BEL','Alexis Jesse Saelemaekers','MID'),
('BEL','Nicolas Thierry Raskin','MID'),
('BEL','Amadou Ba Onana','MID'),
('BEL','Nathan Ngoy','DEF'),
('BEL','Matias Fernandez-Pardo','FWD'),
('EGY','Elsayed Mohamed Mohamed Elshenawy','GK'),
('EGY','Ahmed Ibrahim Yasser','DEF'),
('EGY','Hany Gamal Mohamed Hany','DEF'),
('EGY','Abdelmegeed Abdelsalam Hossam Abdelmaguid','DEF'),
('EGY','Abdelaziz Moustafa Ramy Rabia','DEF'),
('EGY','Abdelmoneim Elsayed Mohamed','DEF'),
('EGY','Ahmed Ibrahim Trezeguet','FWD'),
('EGY','Ashour Metwaly Emam','MID'),
('EGY','Mohamed Abdelkarim Hamza','FWD'),
('EGY','Hamed Mahrous Mohamed Salah','FWD'),
('EGY','Mohamed Zaky Mostafa Zico','MID'),
('EGY','Yousry Fouad Haissem Hassan','FWD'),
('EGY','Mohamed Aboelfetouh Ahmed Fatouh','DEF'),
('EGY','Fathy Abdelhalim Hamdy Fathy','MID'),
('EGY','Hafez Ramadan Karim Hafez','DEF'),
('EGY','Mohamed Soliman Mahdy Soliman','GK'),
('EGY','Mostafa Ahmed Mohanad Lashin','MID'),
('EGY','Aly Elmahdy Nabil','MID'),
('EGY','Attia Fahim Marawan Attia','MID'),
('EGY','Adel Aly Mohamed Ibrahim','FWD'),
('EGY','Saber Abdelmohsen Mahmoud','MID'),
('EGY','Mohamed Abdelsalam Omar','FWD'),
('EGY','Abdelaziz Mohame Mostafa','GK'),
('EGY','Abdelghaffar Abdel Tarek Alaa','DEF'),
('EGY','Mostafa Mohamed Zizo','FWD'),
('EGY','Alaaeldin Soliman Mohamed Alaa','GK'),
('IRN','Ali Reza Beiranvand','GK'),
('IRN','Saleh Hardani','DEF'),
('IRN','Ehsan Hajisafi','DEF'),
('IRN','Shojae Khalilzadeh','DEF'),
('IRN','Milad Mohammadi','DEF'),
('IRN','Saeid Ezatolahi','MID'),
('IRN','Alireza Jahanbakhsh','MID'),
('IRN','Mohammad Mohebbi','MID'),
('IRN','Mehdi Taremi','FWD'),
('IRN','Mehdi Ghayedi','FWD'),
('IRN','Ali Alipour','FWD'),
('IRN','Seyedpayam Niazmand','GK'),
('IRN','Mohammadhossein Kanani','DEF'),
('IRN','Seyed Saman Ghoddos','MID'),
('IRN','Roozbeh Cheshmi','MID'),
('IRN','Mahdi Torabi','MID'),
('IRN','Arya Yousefi','DEF'),
('IRN','Amirhossein Hosseinzadeh','FWD'),
('IRN','Ali Nemati','DEF'),
('IRN','Shahriyar Moghanloo','FWD'),
('IRN','Mohammad Ghorbani','MID'),
('IRN','Seyedhossein Hosseini','GK'),
('IRN','Ramin Rezaeian','DEF'),
('IRN','Dennis Dargahi','FWD'),
('IRN','Danial Iri','DEF'),
('IRN','Amirmohammad Razaghinia','MID'),
('NZL','Maxime Teremoana Crocombe','GK'),
('NZL','Timothy John Payne','DEF'),
('NZL','Francis De Vries','DEF'),
('NZL','Tyler Grant Bindon','DEF'),
('NZL','Michael Joseph Boxall','DEF'),
('NZL','Joe Zen Robert Bell','MID'),
('NZL','Logan Tipene Rogerson','FWD'),
('NZL','Marko Seufatu Nikola Stamenic','MID'),
('NZL','Christopher Grant Wood','FWD'),
('NZL','Sarpreet Singh','MID'),
('NZL','Elijah Henry Just','MID'),
('NZL','Alexander Noah Paulsen','GK'),
('NZL','Liberato Gianpaolo Cacace','DEF'),
('NZL','Alex Arthur Rufer','MID'),
('NZL','Nando Zen Pijnaker','DEF'),
('NZL','Finn Surman','DEF'),
('NZL','Kosta Barbarouses','FWD'),
('NZL','Benjamin Peter Waine','FWD'),
('NZL','Benjamin Craig Old','MID'),
('NZL','Mc (NZL)','MID'),
('NZL','Jesse Carmichael Randall','FWD'),
('NZL','Michael Cornelis Woud','GK'),
('NZL','Ryan Jared Thomas','MID'),
('NZL','Callan Rennie Elliot','DEF'),
('NZL','Lachlan Ryan Bayliss','MID'),
('NZL','Thomas Jefferson Smith','DEF'),
('ESP','David Raya','GK'),
('ESP','Marc Pubill','DEF'),
('ESP','Alejandro Grimaldo','DEF'),
('ESP','Eric Garcia','DEF'),
('ESP','Marcos Llorente','DEF'),
('ESP','Mikel Merino','MID'),
('ESP','Ferran Torres','FWD'),
('ESP','Fabian Ruiz','MID'),
('ESP','Pablo Gavi','MID'),
('ESP','Daniel Olmo','FWD'),
('ESP','Yeremy Jesús Pino','FWD'),
('ESP','Pedro Antonio Porro','DEF'),
('ESP','Joan Garcia','GK'),
('ESP','Aymeric Laporte','DEF'),
('ESP','Alejandro Baena','MID'),
('ESP','Rodrigo Rodri','MID'),
('ESP','Nicholas Williams','FWD'),
('ESP','Martin Zubimendi','MID'),
('ESP','Lamine Yamal Yamal','FWD'),
('ESP','Pedro Pedri','MID'),
('ESP','Mikel Oyarzabal','FWD'),
('ESP','Pau Cubarsi','DEF'),
('ESP','Unai Simon','GK'),
('ESP','Marc Cucurella','DEF'),
('ESP','Victor Munoz','FWD'),
('ESP','Borja Iglesias','FWD'),
('CPV','José Vozinha','GK'),
('CPV','Ianique Stopira','DEF'),
('CPV','Alberto Diney','DEF'),
('CPV','Carlos Pico Lopes','DEF'),
('CPV','Evans Logan Costa','DEF'),
('CPV','Lenini Kevin Pina','MID'),
('CPV','Eduardo Jovane','MID'),
('CPV','Paulo Joao Paulo','MID'),
('CPV','BENCHIMOLGilson Gilson','FWD'),
('CPV','Gregory Jamiro Monteiro','MID'),
('CPV','RODRIGUESGarry Garry','MID'),
('CPV','Salomão Marcio','GK'),
('CPV','CABRALSidny Sidny Lopes','DEF'),
('CPV','Deroy Deroy Duarte','MID'),
('CPV','Michael Laros Duarte','MID'),
('CPV','SEMEDOJair Yannick','MID'),
('CPV','Johnson Willy','MID'),
('CPV','Emanuel Telmo','MID'),
('CPV','Dailon Dailon Livramento','FWD'),
('CPV','Isaac Ryan','FWD'),
('CPV','Miguel Nuno Da Costa','MID'),
('CPV','MOREIRASteven Steven','DEF'),
('CPV','Joaquim Cj Dos Santos','GK'),
('CPV','Fabricio Wagner Pina','DEF'),
('CPV','PIRESKelvin Kelvin','DEF'),
('CPV','Sandro Helio Varela','MID'),
('KSA','Dhahi Nawaf Alaqidi','GK'),
('KSA','Hassan Ali Majrashi','DEF'),
('KSA','Mohammed Ali Lajami','DEF'),
('KSA','Ali Abdulelah Alamri','DEF'),
('KSA','Mohammed Hassan Altambakti','DEF'),
('KSA','Essa Nasser Aldawsari','MID'),
('KSA','Fahad Musab Aljuwayr','MID'),
('KSA','Yahya Aiman Yahya','FWD'),
('KSA','Tariq Feras','FWD'),
('KSA','Mohammed Salem Aldawsari','FWD'),
('KSA','Khalid Saleh','FWD'),
('KSA','Abdullah Saud Abdulhamid','DEF'),
('KSA','Meshari Nawaf Bu Washl','DEF'),
('KSA','Kadish Hassan','DEF'),
('KSA','Mohammed Abdullah Alkhaibari','MID'),
('KSA','Mubarak Ziyad Aljohani','MID'),
('KSA','Essa Khalid Alghannam','FWD'),
('KSA','Mohsen Ala Alhajji','MID'),
('KSA','Abdulrahman Abdullah Alhamddan','FWD'),
('KSA','Ahmed Sultan Mandash','FWD'),
('KSA','Khalil Mohammed Alowais','GK'),
('KSA','Ali Ahmed','GK'),
('KSA','Ibrahim Mohamed','MID'),
('KSA','Saad Moteb Alharbi','DEF'),
('KSA','Abdullatif Jehad Thikri','DEF'),
('KSA','Waheeb Mohammed Abu Alshamat','DEF'),
('URU','Sergio Ramón Rochet','GK'),
('URU','José María Gimenez','DEF'),
('URU','Sebastián Enzo Caceres','DEF'),
('URU','Ronald Federico Araujo','DEF'),
('URU','Manuel Ugarte','MID'),
('URU','Rodrigo Bentancur','MID'),
('URU','Diego Nicolás De La Cruz','MID'),
('URU','Federico Santiago Valverde','MID'),
('URU','Darwin Gabriel Nunez','FWD'),
('URU','Giorgian Daniel De Arrascaeta','MID'),
('URU','Facundo Pellistri','FWD'),
('URU','Santiago Andres Mele','GK'),
('URU','Guillermo Varela','DEF'),
('URU','Agustin Canobbio','MID'),
('URU','Emiliano Martinez','MID'),
('URU','Mathías Olivera','DEF'),
('URU','Matías Nicolas Vina','DEF'),
('URU','Paul Brian Rodriguez','FWD'),
('URU','Rodrigo Sebastian Aguirre','FWD'),
('URU','Maximiliano Javier Araujo','MID'),
('URU','Federico Sebastian Vinas','FWD'),
('URU','Joaquin Piquerez','MID'),
('URU','Nestor Fernando Muslera','GK'),
('URU','Santiago Ignacio Bueno','DEF'),
('URU','Juan Manuel Sanabria','MID'),
('URU','Radrigo Zalazar','MID'),
('FRA','Brice Lauriche Samba','GK'),
('FRA','Malo Arthur Gusto','DEF'),
('FRA','Lucas Digne','DEF'),
('FRA','Dayotchanculle Oswald Upamecano','DEF'),
('FRA','Jules Olivier Kounde','DEF'),
('FRA','Emmanuel Boris Kone','MID'),
('FRA','Masour Ousmane Dembele','FWD'),
('FRA','Aurélien Djani Tchouameni','MID'),
('FRA','Marcus Lilian Thuram','FWD'),
('FRA','Kylian Mbappe','FWD'),
('FRA','Michael Akpovie Olise','FWD'),
('FRA','Bradley Jean-Manuel Essolisa Barcola','FWD'),
('FRA','N''golo Kante','MID'),
('FRA','Adrien Thibault Marie Rabiot','MID'),
('FRA','Ibrahima Konate','DEF'),
('FRA','Mike Peterson Maignan','GK'),
('FRA','William Alain André Gabriel Saliba','DEF'),
('FRA','Warren Marie Jean-Pierre Zaire-Emery','MID'),
('FRA','Théo Bernard François Hernandez','DEF'),
('FRA','Désiré Nonka-Maho Doue','FWD'),
('FRA','Lucas Francois Bernard Hernandez','DEF'),
('FRA','Jean-Philippe Mateta','FWD'),
('FRA','Robin François Philippe Risser','GK'),
('FRA','Mathis Rayan Cherki','MID'),
('FRA','Maghnes Akliouche','MID'),
('FRA','Maxence Guy Lacroix','DEF'),
('SEN','Yehvann Djibril Victor Diouf','GK'),
('SEN','Mamadou Sarr','DEF'),
('SEN','Kalidou Koulibaly','DEF'),
('SEN','Abdoulaye Seck','DEF'),
('SEN','Idrissa Gana Gueye','MID'),
('SEN','Ismaila Pathe Ciss','MID'),
('SEN','Assane Diao','FWD'),
('SEN','Lamine Camara','MID'),
('SEN','Ahmadou Bamba Mbacke Dieng','FWD'),
('SEN','Sadio Mane','FWD'),
('SEN','Nicolas Jackson','FWD'),
('SEN','Pape Cherif Ndiaye','FWD'),
('SEN','Iliman Cheikh Baroy Ndiaye','FWD'),
('SEN','Ismail Joshua Jakobs','DEF'),
('SEN','Krepin Diatta','DEF'),
('SEN','Edouard Osoque Mendy','GK'),
('SEN','Pape Matar Sarr','MID'),
('SEN','Ismaila Sarr','FWD'),
('SEN','Moussa Niakhate','DEF'),
('SEN','Ibrahim Mbaye','FWD'),
('SEN','Habib Mbacke Diarra','MID'),
('SEN','Bara Sapoko Ndiaye','MID'),
('SEN','Mory Diaw','GK'),
('SEN','Antoine Alpha Mendy','DEF'),
('SEN','El Hadji Malick Diouf','DEF'),
('SEN','Pape Alassane Gueye','MID'),
('IRQ','Talib Raheem Fahad Talib','GK'),
('IRQ','Ghareeb Solaka Rebin Sulaka','DEF'),
('IRQ','Haydar Hussein Hussein','DEF'),
('IRQ','Tahseen Abd Zaid Zaid','DEF'),
('IRQ','Hashim Rahman Akam Hashim','DEF'),
('IRQ','Younus Hashim Munaf Younus','DEF'),
('IRQ','Wali Faeq Youssef Amyn','MID'),
('IRQ','Bayesh Kamil Ibrahim Bayesh','MID'),
('IRQ','Ibrahim Karim Ali Alhamadi','FWD'),
('IRQ','Ali Kadhim Mohanad Ali','FWD'),
('IRQ','Ihab Ahmed Ahmed','FWD'),
('IRQ','Hasan Hachim Jalal Hassan','GK'),
('IRQ','Yousif Hashim Ali Yousif','FWD'),
('IRQ','Aamar Iqbal Zidane','MID'),
('IRQ','Hasan Maknazi Ahmed Maknazi','DEF'),
('IRQ','Fouad Aboud Amir Alammari','MID'),
('IRQ','Jasim Elaibi Ali Jasim','FWD'),
('IRQ','Hussein Ghadhban Aymen','FWD'),
('IRQ','Yakob William Kevin Yakob','MID'),
('IRQ','Hazar Anwar Aimar','MID'),
('IRQ','Jabbar Hussein Marko Farji','FWD'),
('IRQ','Basil Fadhil Ahmed','GK'),
('IRQ','Ghazi Salih Merchas','DEF'),
('IRQ','Ismael Khaleel Zaid Ismael','MID'),
('IRQ','Saadoon Abbood Mustafa','DEF'),
('IRQ','Dhia Jirjis Frans','DEF'),
('NOR','Ørjan Haskjold Nyland','GK'),
('NOR','Morten Thorsby','MID'),
('NOR','Kristoffer Vassbakk Köpp Ajer','DEF'),
('NOR','Leo Skiri Ostigard','DEF'),
('NOR','David Møller Moller Wolfe','DEF'),
('NOR','Patrick Berg','MID'),
('NOR','Alexander Sorloth','FWD'),
('NOR','Sander Gard Bolin Berge','MID'),
('NOR','Erling Braut Haaland','FWD'),
('NOR','Martín Odegaard','MID'),
('NOR','Jørgen Strand Strand Larsen','FWD'),
('NOR','Sander Tangvik','GK'),
('NOR','Egil Selvik','GK'),
('NOR','Fredrik Aursnes','MID'),
('NOR','Fredrik André Bjorkan','DEF'),
('NOR','Marcus Holmgren Holmgren Pedersen','DEF'),
('NOR','Torbjørn Lysaker Heggem','DEF'),
('NOR','Kristian Thorstvedt','MID'),
('NOR','Thelonious Gerard Aasgaard','MID'),
('NOR','Antonio Eromonsele Nordby Nusa','FWD'),
('NOR','Andreas Rædergård Schjelderup','MID'),
('NOR','Oscar Bobb','MID'),
('NOR','Jens Petter Hauge','MID'),
('NOR','Sondre Klingen Langas','DEF'),
('NOR','Henrik Sælebakke Falchener','DEF'),
('NOR','Julian Ryerson','FWD'),
('ARG','Juan Agustín Musso','GK'),
('ARG','Marcos Nicolás Senesi','DEF'),
('ARG','Nicolás Alejandro Tagliafico','DEF'),
('ARG','Gonzalo Ariel Montiel','DEF'),
('ARG','Leandro Daniel Paredes','MID'),
('ARG','Lisandro Martinez','DEF'),
('ARG','Rodrigo Javier De Paul','MID'),
('ARG','Valentin Barco','MID'),
('ARG','Julián Alvarez','FWD'),
('ARG','Lionel Andrés Messi','FWD'),
('ARG','Giovani Lo Celso','MID'),
('ARG','Geronimo Rulli','GK'),
('ARG','Cristian Gabriel Romero','DEF'),
('ARG','Exequiel Alejandro Palacios','MID'),
('ARG','Nicolas Ivan Gonzalez','MID'),
('ARG','Thiago Ezequiel Almada','FWD'),
('ARG','Giuliano Simeone','FWD'),
('ARG','Nicolas Paz','FWD'),
('ARG','Nicolas Hernan Gonzalo Otamendi','DEF'),
('ARG','Alexis Mac Allister','MID'),
('ARG','Jose Manuel Alberto Lopez','FWD'),
('ARG','Lautaro Javier Martinez','FWD'),
('ARG','Damián Emiliano Martinez','GK'),
('ARG','Enzo Jeremías Fernandez','MID'),
('ARG','Facundo Axel Medina','DEF'),
('ARG','Nahuel Molina','DEF'),
('ALG','Melvin Feycal Mastil','GK'),
('ALG','Aissa Mandi','DEF'),
('ALG','Achref Abada','DEF'),
('ALG','Mohamed Amine Tougai','DEF'),
('ALG','Zineddine Belaid','DEF'),
('ALG','Ramiz Larbi Zerrouki','MID'),
('ALG','Riyad Karim Mahrez','FWD'),
('ALG','Houssem-Eddine Chaabane Aouar','MID'),
('ALG','Amine Ferid Gouiri','FWD'),
('ALG','Fares Chaibi','MID'),
('ALG','Anis Hadj Moussa','FWD'),
('ALG','Ahmed Nadhir Benbouali','FWD'),
('ALG','Jaouen Djimmy Hadjam','DEF'),
('ALG','Hicham Boudaoui','MID'),
('ALG','Rayan Ait-Nouri','DEF'),
('ALG','Oussama Benbot','GK'),
('ALG','Rafik Belghali','DEF'),
('ALG','Mohammed Elamine Amoura','FWD'),
('ALG','Nabil Bentaleb','MID'),
('ALG','Adil Boulbina','FWD'),
('ALG','Selmane Rami Bensebaini','DEF'),
('ALG','Ibrahim Maza','MID'),
('ALG','Luca Zinedine Zidane','GK'),
('ALG','Yassine Titraoui','MID'),
('ALG','Fares Ghedjemis','FWD'),
('ALG','Samir Sophian Chergui','DEF'),
('AUT','Alexander Schlager','GK'),
('AUT','David Leopold Affengruber','DEF'),
('AUT','Kevin Danso','DEF'),
('AUT','Xaver Schlager','MID'),
('AUT','Stefan Posch','DEF'),
('AUT','Nicolas Seiwald','MID'),
('AUT','Marko Arnautovic','FWD'),
('AUT','David Alaba','DEF'),
('AUT','Marcel Sabitzer','MID'),
('AUT','Florian Grillitsch','MID'),
('AUT','Michael Gregoritsch','FWD'),
('AUT','Florian Wiegele','GK'),
('AUT','Patrick Pentz','GK'),
('AUT','Saša Kalajdzic','FWD'),
('AUT','Philipp Lienhart','DEF'),
('AUT','Phillip Mwene','DEF'),
('AUT','Carney Chibueze Chukwuemeka','MID'),
('AUT','Romano Schmid','MID'),
('AUT','Dejan Ljubicic','MID'),
('AUT','Konrad Laimer','MID'),
('AUT','Patrick Wimmer','FWD'),
('AUT','Alexander Prass','MID'),
('AUT','Marco Friedl','DEF'),
('AUT','Paul Wanner','MID'),
('AUT','Michael Svoboda','DEF'),
('AUT','Alessandro Andre Schoepf','MID'),
('JOR','Mo''ien Hasan Yazeed Abulaila','GK'),
('JOR','Ali Hasan Mohammad','DEF'),
('JOR','Mousa Musallam Abdallah Nasib','DEF'),
('JOR','Ali Mohammad Husam Abudahab','DEF'),
('JOR','Mousa Mahmoud Yazan Alarab','DEF'),
('JOR','Rasem Adel Amer Jamous','MID'),
('JOR','Faisal Yousef Mohammad','FWD'),
('JOR','Mahmoud Ali Noor Alrawabdeh','MID'),
('JOR','Iyad Ali Ali Olwan','FWD'),
('JOR','Mohammad Mousa Mousa Altamari','FWD'),
('JOR','Burhan Shehadeh Odeh Fakhoury','FWD'),
('JOR','Zaid Khaleel Nour Baniateyah','GK'),
('JOR','Nayef Ahmad Mahmoud Almardi','FWD'),
('JOR','Ayed Fadel Rajaei Ayed','MID'),
('JOR','Mohammad Sami Ibrahim','MID'),
('JOR','Majed Jamil Mohammad Abualnadi','DEF'),
('JOR','Amer Saleem Saleem','DEF'),
('JOR','Ahmed Mohammad Mohammad','MID'),
('JOR','Ahmad Salameh Saed','DEF'),
('JOR','Mahmoud Saleh Mohannad Abutaha','MID'),
('JOR','Mahmoud Ahmed Nizar Alrashdan','MID'),
('JOR','Ra''ed Mahmoud Abdallah Alfakhori','GK'),
('JOR','Manel Farhan Ehsan Haddad','DEF'),
('JOR','Ahmad Ali Ali Azaizeh','FWD'),
('JOR','Ratib Mohammad Mohammad Aldaoud','MID'),
('JOR','Said Ghazi Anas Badawi','DEF'),
('POR','Diogo Diogo Costa','GK'),
('POR','SEMEDONélson Nelson','DEF'),
('POR','Rúben Ruben Dias','DEF'),
('POR','Tomás Tomas Araujo','DEF'),
('POR','Diogo Diogo Dalot','DEF'),
('POR','Luiz Matheus','MID'),
('POR','Ronaldo Cristiano Ronaldo','FWD'),
('POR','Miguel Bruno','MID'),
('POR','RAMOSGonçalo Goncalo','FWD'),
('POR','Bernardo Bernardo Silva','MID'),
('POR','João Joao Felix','FWD'),
('POR','Pedro Jose Sa','GK'),
('POR','Renato Renato Veiga','DEF'),
('POR','Gonçalo Goncalo Inacio','DEF'),
('POR','Pedro Joao Neves','MID'),
('POR','António Francisco Trincao','FWD'),
('POR','Alexandre Rafael Leao','FWD'),
('POR','Pedro Pedro Neto','FWD'),
('POR','Manuel Goncalo','FWD'),
('POR','Pedro Joao Cancelo','DEF'),
('POR','Diogo Ruben','MID'),
('POR','Tiago Rui Silva','GK'),
('POR','Vitor Vitinha','MID'),
('POR','Samuel Samu Costa','DEF'),
('POR','Alexandre Nuno','DEF'),
('POR','Francisco Francisco Conceicao','FWD'),
('COD','Lionel Nzau Mpasi','GK'),
('COD','Wan Wan-Bissaka','DEF'),
('COD','Steve Nkanu Kapuadi','DEF'),
('COD','Axel Tuanzebe','DEF'),
('COD','Dylan Buduka Batubinsika','DEF'),
('COD','Ngal’ayel Mukau','MID'),
('COD','Nathanaël Mbuku','MID'),
('COD','Samuel Alain Moutoussamy','MID'),
('COD','Kibambe Brian Cipenga','FWD'),
('COD','Theo Mbulofeko Batombo Bongonda','MID'),
('COD','Gaël Roméo Kakuta','FWD'),
('COD','Joris Kayembe','DEF'),
('COD','Meschack Lina Elia','FWD'),
('COD','Noah Junior Sadiki','MID'),
('COD','Tshibola Tshibola','MID'),
('COD','Timothy Bruce Munzoko Fayulu','GK'),
('COD','Cedric Bakambu','FWD'),
('COD','Charles Monginda Pickel','MID'),
('COD','Mayele Fiston Mayele','FWD'),
('COD','Yoane Wissa','FWD'),
('COD','Matthieu Luka Epolo','GK'),
('COD','Mangulu Chancel Mbemba','DEF'),
('COD','Simon Bokote Banza','FWD'),
('COD','Gédéon Tchingoma Kyatengwa Kalulu','DEF'),
('COD','Edo Kayembe Kayembe','MID'),
('COD','Arthur Fuka Masuaku','DEF'),
('UZB','Utkir Yusupov','GK'),
('UZB','Abdukodir Khusanov','DEF'),
('UZB','Khojiakbar Alijonov','DEF'),
('UZB','Farrukh Sayfiev','DEF'),
('UZB','Rustamjon Ashurmatov','DEF'),
('UZB','Akmal Mozgovoy','MID'),
('UZB','Otabek Shukurov','MID'),
('UZB','Jamshid Iskanderov','MID'),
('UZB','Odiljon Xamrobekov','MID'),
('UZB','Ruslanbek Jiyanov','MID'),
('UZB','Oston Urunov','MID'),
('UZB','Abduvakhid Nematov','GK'),
('UZB','Sherzod Nasrullaev','DEF'),
('UZB','Eldor Shomurodov','FWD'),
('UZB','Umarbek Eshmurodov','DEF'),
('UZB','Botirali Ergashev','GK'),
('UZB','Dostonbek Khamdamov','MID'),
('UZB','Abdulla Abdullaev','DEF'),
('UZB','Azizjon Ganiev','MID'),
('UZB','Azizbek Amonov','FWD'),
('UZB','Igor Sergeev','FWD'),
('UZB','Abbosbek Fayzullaev','MID'),
('UZB','Sherzod Esanov','MID'),
('UZB','Behruzjon Karimov','DEF'),
('UZB','Avazbek Ulmasaliyev','DEF'),
('UZB','Jakhongir Urozov','DEF'),
('COL','David Ospina','GK'),
('COL','Daniel Munoz','DEF'),
('COL','Jhon Janer Lucumi','DEF'),
('COL','Santiago Arias','DEF'),
('COL','Kevin Duvan Castano','MID'),
('COL','Richard Rios','MID'),
('COL','Luis Fernando Diaz','FWD'),
('COL','Jorge Andres Carrascal','MID'),
('COL','Jhon Andrés Cordoba','FWD'),
('COL','James David Rodriguez','MID'),
('COL','Jhon Adolfo Arias','MID'),
('COL','Camilo Andres Vargas','GK'),
('COL','Yerry Fernando Mina','DEF'),
('COL','Gustavo Adolfo Puerta','DEF'),
('COL','Juan Camilo Portilla','MID'),
('COL','Jefferson Andrés Lerma','MID'),
('COL','Johan Andrés Mojica','DEF'),
('COL','Willer Emilio Ditta','DEF'),
('COL','Juan Camilo Hernandez','FWD'),
('COL','Juan Fernando Quintero','MID'),
('COL','Jaminton Leandro Campaz','FWD'),
('COL','Deiver Machado','DEF'),
('COL','Davinson Sanchez','DEF'),
('COL','Álvaro David Montero','GK'),
('COL','Luis Javier Suarez','FWD'),
('COL','Carlos Andrés Gomez','FWD'),
('ENG','Jordan Lee Pickford','GK'),
('ENG','Ezri Ngoyo Konsa','DEF'),
('ENG','Nico Oreilly','DEF'),
('ENG','Declan Rice','MID'),
('ENG','John Stones','DEF'),
('ENG','Keaninkin Marc-Isreal Guehi','DEF'),
('ENG','Bukayo Ayoyinka Saka','FWD'),
('ENG','Elliot Junior Anderson','MID'),
('ENG','Harry Edward Kane','FWD'),
('ENG','Jude Victor William Bellingham','MID'),
('ENG','Marcus Rashford','FWD'),
('ENG','Trevoh Tom Chalobah','DEF'),
('ENG','Dean Bradley Henderson','GK'),
('ENG','Jordan Brian Henderson','MID'),
('ENG','Daniel Johnson Burn','DEF'),
('ENG','Kobbie Boateng Mainoo','MID'),
('ENG','Morgan Elliot Rogers','MID'),
('ENG','Anthony Michael Gordon','FWD'),
('ENG','George Arthur Watkins','FWD'),
('ENG','Azuka Tristan Madueke','FWD'),
('ENG','Eberechi Oluchi Eze','MID'),
('ENG','Ivan Benjamin Elijah Toney','FWD'),
('ENG','James Harrington Trafford','GK'),
('ENG','Reece Lewis James','DEF'),
('ENG','Tehuti Djed-Hotep Spence','DEF'),
('ENG','Jarell Amorin Quansah','DEF'),
('CRO','Dominik Livakovic','GK'),
('CRO','Josip Stanisic','DEF'),
('CRO','Marin Pongracic','DEF'),
('CRO','Joško Gvardiol','DEF'),
('CRO','Duje Caleta-Car','DEF'),
('CRO','Josip Sutalo','DEF'),
('CRO','Nikola Moro','MID'),
('CRO','Mateo Kovacic','MID'),
('CRO','Andrej Kramaric','FWD'),
('CRO','Luka Modric','MID'),
('CRO','Ante Budimir','FWD'),
('CRO','Ivor Pandur','GK'),
('CRO','Nikola Vlasic','MID'),
('CRO','Ivan Perisic','FWD'),
('CRO','Mario Pasalic','MID'),
('CRO','Martin Baturina','MID'),
('CRO','Petar Sucic','MID'),
('CRO','Kristijan Jakic','DEF'),
('CRO','Toni Fruk','MID'),
('CRO','Igor Matanovic','FWD'),
('CRO','Luka Sucic','MID'),
('CRO','Luka Vuskovic','DEF'),
('CRO','Dominik Kotarski','GK'),
('CRO','Marco Pasalic','FWD'),
('CRO','Martin Erlic','DEF'),
('CRO','Petar Musa','FWD'),
('GHA','Lawrence Ati Zigi','GK'),
('GHA','Alidu Seidu','DEF'),
('GHA','Caleb Marfo Yirenkyi','MID'),
('GHA','Jonas Adjei Adjetey','DEF'),
('GHA','Thomas Teye Partey','MID'),
('GHA','Abdul Mumin Mumin','DEF'),
('GHA','Abdul Fatawu Fatawu','FWD'),
('GHA','Kwasi Sibo','MID'),
('GHA','Jordan Pierre Ayew','FWD'),
('GHA','Brandon Michael Clarke Thomas-Asante','FWD'),
('GHA','Antoine Serlom Semenyo','MID'),
('GHA','Joseph Tetteh Anang','GK'),
('GHA','Christopher Bonsu Bonsu Baah','FWD'),
('GHA','Gideon Mensah','DEF'),
('GHA','Elisha Owusu','MID'),
('GHA','Benjamin Asare','GK'),
('GHA','Abdul Rahman Rahman','DEF'),
('GHA','Jerome Opoku','DEF'),
('GHA','Inaki Williams','FWD'),
('GHA','Augustine Boakye','MID'),
('GHA','Kojo Peprah Oppong','DEF'),
('GHA','Kamal Deen Sulemana','FWD'),
('GHA','Derrick Luckassen','DEF'),
('GHA','Ernest Nuamah Nuamah','FWD'),
('GHA','Prince Kwabena Adu','FWD'),
('GHA','Marvin Elom Senaya','DEF'),
('PAN','Luis Ricardo Mejia','GK'),
('PAN','Cesar Rodolfo Blackman','DEF'),
('PAN','Jose Angel Cordoba','DEF'),
('PAN','Fidel Escobar','DEF'),
('PAN','Edgardo Issac Farina','DEF'),
('PAN','Cristian Jesus Martinez','MID'),
('PAN','Jose Luis Rodriguez','MID'),
('PAN','Adalberto Eliecer Carrasquilla','MID'),
('PAN','Tomas Abdiel Rodriguez','FWD'),
('PAN','Ismael Diaz','MID'),
('PAN','Edgar Yoel Barcenas','MID'),
('PAN','Cesar Jair Samudio','GK'),
('PAN','Jiovany Javier Ramos','DEF'),
('PAN','Carlos Miguel Harvey','DEF'),
('PAN','Eric Javier Davis','DEF'),
('PAN','Andres Alberto Andrade','DEF'),
('PAN','Jose Fajardo','FWD'),
('PAN','Cecilio Alfonso Waterman','FWD'),
('PAN','Alberto Abdiel Quintero','MID'),
('PAN','Anibal Casis Godoy','MID'),
('PAN','Cesar Augusto Yanis','MID'),
('PAN','Orlando Mosquera','GK'),
('PAN','Michael Amir Murillo','DEF'),
('PAN','Azarías Emmanuel Londono','FWD'),
('PAN','Roderick Alonso Miller','DEF'),
('PAN','Jorge Abdiel Gutierrez','DEF');
